server:
  port: 8084

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
        - id: booking
          uri: lb://BOOKING
          predicates:
            - Path=/api/v1/bookings/**
        - id: event
          uri: lb://EVENT
          predicates:
            - Path=/api/v1/events/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/ticket-manager-realm

keycloak:
  realm: ticket-manager-realm
  auth-server-url: http://localhost:8085/auth
  resource: ticket-manager-apigw
  credentials:
    secret: RKUjRqsUMzf7UWhcIZ7Ik5RjGsgmO3Gd
  bearer-only: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true