server:
  port: 8084

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/customers/v3/api-docs, /api/v1/customers/**
        - id: booking
          uri: lb://BOOKING
          predicates:
            - Path=/bookings/v3/api-docs, /api/v1/bookings/**
        - id: event
          uri: lb://EVENT
          predicates:
            - Path=/api/v1/events/**
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/ticket-manager-realm

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /customers/v3/api-docs
        name: Customer Service
      - url: /bookings/v3/api-docs
        name: Booking Service


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true



