server:
  port: 8099
spring:
  profiles:
    active: local
  config:
    import:
      - optional:classpath:ai-agent-tools.yml
  application:
    name: ai-agent
openapi:
  info:
    title: AI Agent Doc
    version: 1.0.0
  service:
    description: AI Agent APIs

ai-agent:
  answer:
    synthesizer: fake
