server:
  port: 8086
spring:
  application:
    name: cart
  datasource:
    password: password
    url: jdbc:postgresql://localhost:51/cart
    username: admin
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    change-log: classpath:liquibase-changelog.xml
    drop-first: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/ticket-manager-realm
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
openapi:
  info:
    title: Cart Doc
    version: 1.0.0
  service:
    description: Cart APIs
    url: http://localhost:8086
