--liquibase formatted sql
--changeset kkosmala:7
-- Utworzenie tabeli images
CREATE TABLE image (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL,
                       description VARCHAR(255),
                       thumb_image VARCHAR(255)
);

-- Tabela pośrednia dla relacji wiele-do-wielu
CREATE TABLE event_image (
                             event_id BIGINT NOT NULL,
                             image_id BIGINT NOT NULL,
                             PRIMARY KEY (event_id, image_id),
                             CONSTRAINT fk_event FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE,
                             CONSTRAINT fk_image FOREIGN KEY (image_id) REFERENCES image (id) ON DELETE CASCADE
);